In [2]:
import numpy as np

In [3]:
np.logspace(-4,4,20)

array([1.00000000e-04, 2.63665090e-04, 6.95192796e-04, 1.83298071e-03,
       4.83293024e-03, 1.27427499e-02, 3.35981829e-02, 8.85866790e-02,
       2.33572147e-01, 6.15848211e-01, 1.62377674e+00, 4.28133240e+00,
       1.12883789e+01, 2.97635144e+01, 7.84759970e+01, 2.06913808e+02,
       5.45559478e+02, 1.43844989e+03, 3.79269019e+03, 1.00000000e+04])

In [4]:
np.linspace(-4,4,20)

array([-4.        , -3.57894737, -3.15789474, -2.73684211, -2.31578947,
       -1.89473684, -1.47368421, -1.05263158, -0.63157895, -0.21052632,
        0.21052632,  0.63157895,  1.05263158,  1.47368421,  1.89473684,
        2.31578947,  2.73684211,  3.15789474,  3.57894737,  4.        ])

In [7]:
np.arange(100,1000,200)

array([100, 300, 500, 700, 900])

In [8]:
np.arange(600,900,100)

array([600, 700, 800])

In [9]:
np.arange(3,6,1)

array([3, 4, 5])

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
plt.rcParams["figure.figsize"] = [7.00, 3.50]
plt.rcParams["figure.autolayout"] = True
x = ['A', 'B', 'C', 'D', 'E']
y = [1, 3, 2, 0, 4]
percentage = [10, 30, 20, 0, 40]
ax = sns.barplot(x=x, y=y, palette='PuBuGn_r')
patches = ax.patches
for i in range(len(patches)):
   x = patches[i].get_x() + patches[i].get_width()/2
   y = patches[i].get_height()+.05
   ax.annotate('{:.1f}%'.format(percentage[i]), (x, y), ha='center')
plt.show()

In [1]:
from dataclasses import dataclass
@dataclass 
class DataingestionConfiq:
    raw_data_path : str = os.path.join("Dataset", "raw_data.csv")

'd:\\Faisal\\Projects\\end_to_end_hd'

In [24]:
def get_list(n,y):
    x = n + y
    y = n * y
    z = n / y

    return x,y,z

result = get_list(10,5)
# the_number_of_return_values = 1 if type(result) is not tuple else len(result)
# the_number_of_return_values
type(result)


tuple

In [10]:
def get_list(n,y):
    x = n + y
    y = n * y
    z = n / y

    return (x,y,z)

x,y,z = get_list(10,5)
print(x)
print(y)
print(z)



15
50
0.2


In [29]:
import numpy as np
a = np.arange(100,510,100)
a

array([100, 200, 300, 400, 500])

In [ ]:
# logistic_reg_param =['penalty' : ['l1', 'l2', 'elasticnet', 'none'],
#     'C' : np.logspace(-4, 4, 20),
#     'solver' : ['lbfgs','newton-cg','liblinear','sag','saga'],
#     'max_iter' : [100, 1000,2500, 5000]]

# "RandomForestClassifier" : {"n_estimators" : np.arange(100,510,100),
#                                      "max_features" : ['auto', 'sqrt']},

                                   
# "KNeighborsClassifier" : { 'n_neighbors' : [5,7,9,11,13,15],
#                'weights' : ['uniform','distance'],
#             #    'metric' : ['minkowski','euclidean','manhattan']
#                }

# # 'C': [0.1, 1, 10, 100, 1000],
# #         gamma': [1, 0.1, 0.01, 0.001, 0.0001],
# #               'kernel': ['rbf','linear']

# 'loss': ['deviance', 'exponential'],
#     'learning_rate': [0.001, 0.1, 1, 10],
#     'n_estimators': [100, 150, 180, 200]

In [35]:
np.random.seed(42)
l = np.random.randint(1,10,(7,7))
l

array([[7, 4, 8, 5, 7, 3, 7],
       [8, 5, 4, 8, 8, 3, 6],
       [5, 2, 8, 6, 2, 5, 1],
       [6, 9, 1, 3, 7, 4, 9],
       [3, 5, 3, 7, 5, 9, 7],
       [2, 4, 9, 2, 9, 5, 2],
       [4, 7, 8, 3, 1, 4, 2]])

In [36]:
l[:,-1]

array([7, 6, 1, 9, 7, 2, 2])

In [39]:
l[:,:-1]

array([[7, 4, 8, 5, 7, 3],
       [8, 5, 4, 8, 8, 3],
       [5, 2, 8, 6, 2, 5],
       [6, 9, 1, 3, 7, 4],
       [3, 5, 3, 7, 5, 9],
       [2, 4, 9, 2, 9, 5],
       [4, 7, 8, 3, 1, 4]])